import jsPDF from "jspdf";
import { supabase } from "@/integrations/supabase/client";

const KIFEDHA_GOLD: [number, number, number] = [245, 158, 11];
const INK: [number, number, number] = [17, 24, 39];
const MUTED: [number, number, number] = [107, 114, 128];

const fmt = (n: number) => `KES ${Math.round(n).toLocaleString()}`;

export interface ReportContext {
  userId: string;
  userName: string | null;
  userEmail: string | null;
}

export async function generateFinancialReport(ctx: ReportContext): Promise<void> {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 16;
  let y = 0;

  const drawHeader = () => {
    doc.setFillColor(...KIFEDHA_GOLD);
    doc.rect(0, 0, pageW, 24, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Kifedha", margin, 15);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("Personal Financial Blueprint", margin, 20);
    doc.text(new Date().toLocaleDateString(), pageW - margin, 15, { align: "right" });
    if (ctx.userName) doc.text(ctx.userName, pageW - margin, 20, { align: "right" });
    y = 34;
  };

  const drawFooter = (pageNum: number, total: number) => {
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`Generated by Kifedha · kifedha-grow-wealth.lovable.app`, margin, pageH - 8);
    doc.text(`Page ${pageNum} of ${total}`, pageW - margin, pageH - 8, { align: "right" });
  };

  const heading = (txt: string) => {
    if (y > pageH - 40) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...INK);
    doc.text(txt, margin, y);
    doc.setDrawColor(...KIFEDHA_GOLD);
    doc.setLineWidth(0.6);
    doc.line(margin, y + 1.5, margin + 30, y + 1.5);
    y += 8;
  };

  const row = (label: string, value: string, opts: { bold?: boolean; color?: [number, number, number] } = {}) => {
    if (y > pageH - 20) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(10);
    doc.setTextColor(...(opts.color ?? INK));
    doc.text(label, margin, y);
    doc.text(value, pageW - margin, y, { align: "right" });
    y += 6;
  };

  const para = (txt: string) => {
    if (y > pageH - 24) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    const lines = doc.splitTextToSize(txt, pageW - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 2;
  };

  drawHeader();

  // Cover summary
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...INK);
  doc.text("Your Financial Blueprint", margin, y);
  y += 8;
  para(
    `Prepared for ${ctx.userName || ctx.userEmail || "you"} on ${new Date().toLocaleDateString()}. ` +
    `This report summarises your income allocation, debt plan, protection coverage and savings goals — based on the data you have entered in Kifedha.`
  );
  y += 4;

  // ---- Allocation
  const { data: alloc } = await supabase
    .from("user_allocations")
    .select("*")
    .eq("user_id", ctx.userId)
    .order("updated_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  heading("Income allocation");
  if (alloc) {
    row("Monthly income", fmt(Number((alloc as any).monthly_income)), { bold: true });
    y += 2;
    row(`Needs (${(alloc as any).needs_percent}%)`, fmt(Number((alloc as any).needs_amount)));
    row(`Savings (${(alloc as any).savings_percent}%)`, fmt(Number((alloc as any).savings_amount)));
    row(`Investments (${(alloc as any).investments_percent}%)`, fmt(Number((alloc as any).investments_amount)));
    row(`Protection (${(alloc as any).protection_percent}%)`, fmt(Number((alloc as any).protection_amount)));
  } else {
    para("No allocation saved yet. Open the Income Allocator to create one.");
  }
  y += 4;

  // ---- Debts
  const { data: debts } = await supabase
    .from("user_debts").select("*").eq("user_id", ctx.userId).order("interest_rate", { ascending: false });

  heading("Debt plan");
  if (debts && debts.length > 0) {
    let totalDebt = 0;
    let totalMin = 0;
    for (const d of debts as any[]) {
      totalDebt += Number(d.amount);
      totalMin += Number(d.min_payment);
      row(`${d.name} @ ${Number(d.interest_rate).toFixed(1)}%`, fmt(Number(d.amount)));
    }
    y += 2;
    row("Total debt", fmt(totalDebt), { bold: true });
    row("Total min. payments", fmt(totalMin), { bold: true });
    y += 2;
    para("Recommended strategy: Avalanche — pay minimums on every debt, then channel any surplus into the debt with the highest interest rate.");
  } else {
    para("No debts recorded — great job staying debt-free.");
  }
  y += 4;

  // ---- Protection
  const { data: gap } = await supabase
    .from("user_protection_gaps")
    .select("*")
    .eq("user_id", ctx.userId)
    .order("assessed_at", { ascending: false })
    .limit(1).maybeSingle();

  heading("Protection & insurance");
  if (gap) {
    row("Life insurance gap", fmt(Number((gap as any).life_insurance_gap)));
    row("Health insurance gap", fmt(Number((gap as any).health_insurance_gap)));
    row("Income protection gap", fmt(Number((gap as any).income_protection_gap)));
    y += 1;
    row("Total protection gap", fmt(Number((gap as any).total_gap)), { bold: true, color: KIFEDHA_GOLD });
    row("Protection score", `${(gap as any).protection_score}/100`, { bold: true });
  } else {
    para("Protection gap not yet calculated. Run the Protection Calculator for a personalised assessment.");
  }
  y += 4;

  // ---- Goals
  const { data: goals } = await supabase
    .from("user_goals").select("*").eq("user_id", ctx.userId).order("created_at");

  heading("Savings goals");
  if (goals && goals.length > 0) {
    for (const g of goals as any[]) {
      const pct = Number(g.target_amount) > 0
        ? Math.round((Number(g.current_amount) / Number(g.target_amount)) * 100)
        : 0;
      row(`${g.goal_type} (${pct}%)`, `${fmt(Number(g.current_amount))} / ${fmt(Number(g.target_amount))}`);
    }
  } else {
    para("No goals set yet. Add up to 2 goals on Free, or unlimited on Premium.");
  }
  y += 6;

  // Action checklist
  heading("Next actions");
  para("• Review your allocation each month and rebalance after raises or bonuses.");
  para("• Top up your emergency fund until it covers 3–6 months of essential expenses.");
  para("• Close the protection gap before chasing higher-risk investments.");
  para("• Increase your highest-interest debt payment by any surplus from cutting spending.");

  // Footers
  const total = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) { doc.setPage(i); drawFooter(i, total); }

  const filename = `kifedha-blueprint-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
