import jsPDF from "jspdf";
import { supabase } from "@/integrations/supabase/client";

const KIFEDHA_GOLD: [number, number, number] = [245, 158, 11];
const INK: [number, number, number] = [17, 24, 39];
const MUTED: [number, number, number] = [107, 114, 128];

const fmt = (n: number) => `KES ${Math.round(n).toLocaleString()}`;

export interface ReportContext {
  userId: string;
  userName: string | null;
  userEmail: string | null;
}

export async function generateFinancialReport(ctx: ReportContext): Promise<void> {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 16;
  let y = 0;

  const drawHeader = () => {
    doc.setFillColor(...KIFEDHA_GOLD);
    doc.rect(0, 0, pageW, 24, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Kifedha", margin, 15);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("Personal Financial Blueprint", margin, 20);
    doc.text(new Date().toLocaleDateString(), pageW - margin, 15, { align: "right" });
    if (ctx.userName) doc.text(ctx.userName, pageW - margin, 20, { align: "right" });
    y = 34;
  };

  const drawFooter = (pageNum: number, total: number) => {
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`Generated by Kifedha · kifedha-grow-wealth.lovable.app`, margin, pageH - 8);
    doc.text(`Page ${pageNum} of ${total}`, pageW - margin, pageH - 8, { align: "right" });
  };

  const heading = (txt: string) => {
    if (y > pageH - 40) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...INK);
    doc.text(txt, margin, y);
    doc.setDrawColor(...KIFEDHA_GOLD);
    doc.setLineWidth(0.6);
    doc.line(margin, y + 1.5, margin + 30, y + 1.5);
    y += 8;
  };

  const row = (label: string, value: string, opts: { bold?: boolean; color?: [number, number, number] } = {}) => {
    if (y > pageH - 20) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(10);
    doc.setTextColor(...(opts.color ?? INK));
    doc.text(label, margin, y);
    doc.text(value, pageW - margin, y, { align: "right" });
    y += 6;
  };

  const para = (txt: string) => {
    if (y > pageH - 24) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    const lines = doc.splitTextToSize(txt, pageW - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 2;
  };

  drawHeader();

  // Cover summary
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...INK);
  doc.text("Your Financial Blueprint", margin, y);
  y += 8;
  para(
    `Prepared for ${ctx.userName || ctx.userEmail || "you"} on ${new Date().toLocaleDateString()}. ` +
    `This report summarises your income allocation, debt plan, protection coverage and savings goals — based on the data you have entered in Kifedha.`
  );
  y += 4;

  // ---- Allocation
  const { data: alloc } = await supabase
    .from("user_allocations")
    .select("*")
    .eq("user_id", ctx.userId)
    .order("updated_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  heading("Income allocation");
  if (alloc) {
    row("Monthly income", fmt(Number((alloc as any).monthly_income)), { bold: true });
    y += 2;
    row(`Needs (${(alloc as any).needs_percent}%)`, fmt(Number((alloc as any).needs_amount)));
    row(`Savings (${(alloc as any).savings_percent}%)`, fmt(Number((alloc as any).savings_amount)));
    row(`Investments (${(alloc as any).investments_percent}%)`, fmt(Number((alloc as any).investments_amount)));
    row(`Protection (${(alloc as any).protection_percent}%)`, fmt(Number((alloc as any).protection_amount)));
  } else {
    para("No allocation saved yet. Open the Income Allocator to create one.");
  }
  y += 4;

  // ---- Debts
  const { data: debts } = await supabase
    .from("user_debts").select("*").eq("user_id", ctx.userId).order("interest_rate", { ascending: false });

  heading("Debt plan");
  if (debts && debts.length > 0) {
    let totalDebt = 0;
    let totalMin = 0;
    for (const d of debts as any[]) {
      totalDebt += Number(d.amount);
      totalMin += Number(d.min_payment);
      row(`${d.name} @ ${Number(d.interest_rate).toFixed(1)}%`, fmt(Number(d.amount)));
    }
    y += 2;
    row("Total debt", fmt(totalDebt), { bold: true });
    row("Total min. payments", fmt(totalMin), { bold: true });
    y += 2;
    para("Recommended strategy: Avalanche — pay minimums on every debt, then channel any surplus into the debt with the highest interest rate.");
  } else {
    para("No debts recorded — great job staying debt-free.");
  }
  y += 4;

  // ---- Protection
  const { data: gap } = await supabase
    .from("user_protection_gaps")
    .select("*")
    .eq("user_id", ctx.userId)
    .order("assessed_at", { ascending: false })
    .limit(1).maybeSingle();

  heading("Protection & insurance");
  if (gap) {
    row("Life insurance gap", fmt(Number((gap as any).life_insurance_gap)));
    row("Health insurance gap", fmt(Number((gap as any).health_insurance_gap)));
    row("Income protection gap", fmt(Number((gap as any).income_protection_gap)));
    y += 1;
    row("Total protection gap", fmt(Number((gap as any).total_gap)), { bold: true, color: KIFEDHA_GOLD });
    row("Protection score", `${(gap as any).protection_score}/100`, { bold: true });
  } else {
    para("Protection gap not yet calculated. Run the Protection Calculator for a personalised assessment.");
  }
  y += 4;

  // ---- Goals
  const { data: goals } = await supabase
    .from("user_goals").select("*").eq("user_id", ctx.userId).order("created_at");

  heading("Savings goals");
  if (goals && goals.length > 0) {
    for (const g of goals as any[]) {
      const pct = Number(g.target_amount) > 0
        ? Math.round((Number(g.current_amount) / Number(g.target_amount)) * 100)
        : 0;
      row(`${g.goal_type} (${pct}%)`, `${fmt(Number(g.current_amount))} / ${fmt(Number(g.target_amount))}`);
    }
  } else {
    para("No goals set yet. Add up to 2 goals on Free, or unlimited on Premium.");
  }
  y += 6;

  // Action checklist
  heading("Next actions");
  para("• Review your allocation each month and rebalance after raises or bonuses.");
  para("• Top up your emergency fund until it covers 3–6 months of essential expenses.");
  para("• Close the protection gap before chasing higher-risk investments.");
  para("• Increase your highest-interest debt payment by any surplus from cutting spending.");

  // Footers
  const total = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) { doc.setPage(i); drawFooter(i, total); }

  const filename = `kifedha-blueprint-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

// ---------- Shared branded doc helper ----------
function startBrandedDoc(ctx: ReportContext, title: string, subtitle: string) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 16;
  const state = { y: 0 };

  const drawHeader = () => {
    doc.setFillColor(...KIFEDHA_GOLD);
    doc.rect(0, 0, pageW, 24, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Kifedha", margin, 15);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(subtitle, margin, 20);
    doc.text(new Date().toLocaleDateString(), pageW - margin, 15, { align: "right" });
    if (ctx.userName) doc.text(ctx.userName, pageW - margin, 20, { align: "right" });
    state.y = 34;
  };

  const drawFooter = (pageNum: number, total: number) => {
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`Generated by Kifedha · kifedha-grow-wealth.lovable.app`, margin, pageH - 8);
    doc.text(`Page ${pageNum} of ${total}`, pageW - margin, pageH - 8, { align: "right" });
  };

  const heading = (txt: string) => {
    if (state.y > pageH - 40) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...INK);
    doc.text(txt, margin, state.y);
    doc.setDrawColor(...KIFEDHA_GOLD);
    doc.setLineWidth(0.6);
    doc.line(margin, state.y + 1.5, margin + 30, state.y + 1.5);
    state.y += 8;
  };

  const row = (label: string, value: string, opts: { bold?: boolean; color?: [number, number, number] } = {}) => {
    if (state.y > pageH - 20) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(10);
    doc.setTextColor(...(opts.color ?? INK));
    doc.text(label, margin, state.y);
    doc.text(value, pageW - margin, state.y, { align: "right" });
    state.y += 6;
  };

  const para = (txt: string) => {
    if (state.y > pageH - 24) { doc.addPage(); drawHeader(); }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    const lines = doc.splitTextToSize(txt, pageW - margin * 2);
    doc.text(lines, margin, state.y);
    state.y += lines.length * 5 + 2;
  };

  drawHeader();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...INK);
  doc.text(title, margin, state.y);
  state.y += 8;

  const finalise = (filename: string) => {
    const total = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= total; i++) { doc.setPage(i); drawFooter(i, total); }
    doc.save(filename);
  };

  const addY = (n: number) => { state.y += n; };

  return { heading, row, para, finalise, addY };
}

// ---------- Net Worth Snapshot ----------
export async function generateNetWorthSnapshot(ctx: ReportContext): Promise<void> {
  const r = startBrandedDoc(ctx, "Net Worth Snapshot", "Net worth snapshot");

  r.para(
    `Snapshot for ${ctx.userName || ctx.userEmail || "you"} as of ${new Date().toLocaleDateString()}. ` +
    `This statement totals your tracked assets (savings goals + cash buffer) against your tracked liabilities (outstanding debts).`
  );
  r.addY(2);

  const [{ data: goals }, { data: debts }, { data: alloc }] = await Promise.all([
    supabase.from("user_goals").select("goal_type,current_amount,target_amount").eq("user_id", ctx.userId),
    supabase.from("user_debts").select("name,amount").eq("user_id", ctx.userId).eq("is_paid_off", false),
    supabase.from("user_allocations").select("savings_amount").eq("user_id", ctx.userId).order("updated_at", { ascending: false }).limit(1).maybeSingle(),
  ]);

  let assets = 0;
  r.heading("Assets");
  if (goals && goals.length > 0) {
    for (const g of goals as any[]) {
      const v = Number(g.current_amount) || 0;
      assets += v;
      r.row(`${g.goal_type} (saved)`, fmt(v));
    }
  }
  const monthlySavings = Number((alloc as any)?.savings_amount ?? 0);
  if (monthlySavings > 0) r.row("Monthly savings capacity", fmt(monthlySavings));
  if (assets === 0) r.para("No saved goal balances yet — start by funding an emergency fund.");
  r.addY(1);
  r.row("Total assets", fmt(assets), { bold: true });
  r.addY(4);

  let liabilities = 0;
  r.heading("Liabilities");
  if (debts && debts.length > 0) {
    for (const d of debts as any[]) {
      const v = Number(d.amount) || 0;
      liabilities += v;
      r.row(d.name, fmt(v));
    }
  } else {
    r.para("No active debts recorded.");
  }
  r.addY(1);
  r.row("Total liabilities", fmt(liabilities), { bold: true });
  r.addY(4);

  r.heading("Net worth");
  const net = assets - liabilities;
  r.row("Assets − Liabilities", fmt(net), { bold: true, color: net >= 0 ? [16, 122, 87] : [220, 38, 38] });
  r.addY(2);
  r.para(
    net >= 0
      ? "You are in positive territory. Keep growing assets faster than liabilities to compound your net worth."
      : "Your liabilities exceed your assets. Prioritise the avalanche method on high-interest debts and build a 1-month cash buffer first."
  );

  r.finalise(`kifedha-net-worth-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ---------- Monthly P&L ----------
type PLTx = { date: string | Date; type: "income" | "expense"; amount: number; category: string };

export async function generateMonthlyPL(ctx: ReportContext, transactions: PLTx[]): Promise<void> {
  const r = startBrandedDoc(ctx, "Monthly P&L Statement", "Profit & loss statement");

  const now = new Date();
  const month = now.toLocaleString(undefined, { month: "long", year: "numeric" });
  r.para(
    `Profit & loss for ${ctx.userName || ctx.userEmail || "you"} — ${month}. ` +
    `Built from transactions you logged this calendar month in Kifedha.`
  );
  r.addY(2);

  const thisMonth = transactions.filter((t) => {
    const d = new Date(t.date);
    return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
  });

  const incomeByCat: Record<string, number> = {};
  const expenseByCat: Record<string, number> = {};
  let income = 0;
  let expense = 0;
  for (const t of thisMonth) {
    const amt = Number(t.amount) || 0;
    if (t.type === "income") {
      income += amt;
      incomeByCat[t.category || "Other"] = (incomeByCat[t.category || "Other"] || 0) + amt;
    } else {
      expense += amt;
      expenseByCat[t.category || "Other"] = (expenseByCat[t.category || "Other"] || 0) + amt;
    }
  }

  r.heading("Income");
  const incEntries = Object.entries(incomeByCat).sort((a, b) => b[1] - a[1]);
  if (incEntries.length === 0) r.para("No income recorded this month.");
  for (const [cat, v] of incEntries) r.row(cat, fmt(v));
  r.addY(1);
  r.row("Total income", fmt(income), { bold: true });
  r.addY(4);

  r.heading("Expenses");
  const expEntries = Object.entries(expenseByCat).sort((a, b) => b[1] - a[1]);
  if (expEntries.length === 0) r.para("No expenses recorded this month.");
  for (const [cat, v] of expEntries) r.row(cat, fmt(v));
  r.addY(1);
  r.row("Total expenses", fmt(expense), { bold: true });
  r.addY(4);

  r.heading("Net result");
  const net = income - expense;
  const savingsRate = income > 0 ? Math.round((net / income) * 100) : 0;
  r.row("Net (income − expenses)", fmt(net), { bold: true, color: net >= 0 ? [16, 122, 87] : [220, 38, 38] });
  r.row("Savings rate", `${savingsRate}%`, { bold: true });
  r.addY(2);
  r.para(
    savingsRate >= 20
      ? "Strong month — saving 20%+ puts you ahead of most Kenyan households. Channel surplus to high-interest debt or growth investments."
      : savingsRate >= 0
        ? "Positive month but below the 20% target. Review your top 2 expense categories above for one cut."
        : "You spent more than you earned this month. Pause discretionary categories and rebuild a 1-month buffer."
  );

  r.finalise(`kifedha-pl-${now.toISOString().slice(0, 7)}.pdf`);
}
